# Generated by Django 4.2.7 on 2023-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
