# Generated by Django 4.2.7 on 2023-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Auth',
            fields=[
                ('user_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('authorized', models.IntegerField()),
            ],
        ),
    ]
